# Generated by Django 3.2.6 on 2021-10-13 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('doctor', models.CharField(choices=[('doctor1', 'Doctor1'), ('doctor2', 'Doctor2'), ('doctor3', 'Doctor3')], default='doctor1', max_length=10)),
                ('message', models.TextField(max_length=300)),
                ('time', models.CharField(choices=[('07:00-08:00', '07:00-08:00'), ('08:00-09:00', '08:00-09:00'), ('09:00-10:00', '09:00-10:00'), ('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('13:00-14:00', '13:00-14:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00'), ('16:00-17:00', '16:00-17:00')], default='07:00-08:00', max_length=15)),
                ('date', models.DateField(blank=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
